import { Roboto } from "next/font/google";
import Header from "@/components/layout/Header";

import "./globals.css";
import { AppProvider } from "@/components/AppContext";
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "700"], // Optional: Regular & Bold
});

export const metadata = {
  title: "PopMart E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

        <body className={`${roboto.variable} antialiased`}>

          <main className="max-w-7xl mx-auto px-4">
            <AppProvider>
              <Header />
              {children}
            </AppProvider>
          </main>
        </body>
    </html>
  );
}
