import { Roboto } from "next/font/google";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "700"], // Optional: Regular & Bold
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

        <body className={`${roboto.variable} antialiased`}>
          <main className="max-w-7xl mx-auto px-4">
            {children}
          </main>
        </body>
    </html>
  );
}
